using System.Windows;

namespace ES2MD;

/// <summary>
/// Generic helper functions and global variables
/// </summary>
internal static class Common
{
	public static Dictionary<string, string> actors = new([
		new("ACTOR_ADVENTURE_NPC1", ""),
		new("ACTOR_ADVENTURE_NPC2", ""),
		new("ACTOR_ADVENTURE_NPC3", ""),
		new("ACTOR_ATTENDANT_MANAFI", "Manaphy"),
		new("ACTOR_ATTENDANT1", "(Partner)"),
		new("ACTOR_ATTENDANT2", ""),
		new("ACTOR_NPC_AABOKKU", "Arbok"),
		new("ACTOR_NPC_AAMARUDO", "Armaldo"),
		new("ACTOR_NPC_AGUNOMU", "Azelf"),
		new("ACTOR_NPC_BANEBUU", "Spoink"),
		new("ACTOR_NPC_BARIYAADO", "Mr. Mime"),
		new("ACTOR_NPC_BARUBIITO1", "Volbeat"),
		new("ACTOR_NPC_BARUBIITO2", "Volbeat"),
		new("ACTOR_NPC_BARUBIITO3", "Volbeat"),
		new("ACTOR_NPC_BARUBIITO4", "Volbeat"),
		new("ACTOR_NPC_BETOBETAA", "Grimer"),
		new("ACTOR_NPC_BETOBETAA2", "Volbeat"),
		new("ACTOR_NPC_BETOBETAA3", "Volbeat"),
		new("ACTOR_NPC_BETOBETAA4", "Volbeat"),
		new("ACTOR_NPC_BETOBETAA5", "Volbeat"),
		new("ACTOR_NPC_BETOBETON", "Muk"),
		new("ACTOR_NPC_BETOBETON2", "Muk"),
		new("ACTOR_NPC_BETOBETON3", "Muk"),
		new("ACTOR_NPC_BIIDARU", "Bibarel"),
		new("ACTOR_NPC_BIPPA", "Bidoof"),
		new("ACTOR_NPC_BIPPA_BRO", "Bidoof"),
		new("ACTOR_NPC_BIPPA_SIS", "Bidoof"),
		new("ACTOR_NPC_BOSUGODORA", "Aggron"),
		new("ACTOR_NPC_BUUBAAN", "Magmortar"),
		new("ACTOR_NPC_CHAAREMU", "Medicham"),
		new("ACTOR_NPC_CHIRIIN", "Chimecho"),
		new("ACTOR_NPC_DAAKURAI", "Darkrai"),
		new("ACTOR_NPC_DAGUTORIO", "Dugtrio"),
		new("ACTOR_NPC_DARK_DIARUGA", "Primal Dialga"),
		new("ACTOR_NPC_DARK_PUKURIN", "Primal Wigglytuff"),
		new("ACTOR_NPC_DEBUG", "(Debug)"),
		new("ACTOR_NPC_DENRYUU", "Ampharos"),
		new("ACTOR_NPC_DIARUGA", "Dialga"),
		new("ACTOR_NPC_DIGUDA", "Diglett"),
		new("ACTOR_NPC_DOGAASU", "Koffing"),
		new("ACTOR_NPC_DOGOOMU", "Loudred"),
		new("ACTOR_NPC_DORAPION", "Drapion"),
		new("ACTOR_NPC_DOSAIDON", "Rhyperior"),
		new("ACTOR_NPC_EMURITTO", "Mesprit"),
		new("ACTOR_NPC_FIONE1", "Phione"),
		new("ACTOR_NPC_FIONE2", "Phione"),
		new("ACTOR_NPC_FIONE3", "Phione"),
		new("ACTOR_NPC_FIONE4", "Phione"),
		new("ACTOR_NPC_FIONE5", "Phione"),
		new("ACTOR_NPC_FIONE6", "Phione"),
		new("ACTOR_NPC_FIONE7", "Phione"),
		new("ACTOR_NPC_FIONE8", "Phione"),
		new("ACTOR_NPC_FURIIZAA", "Articuno"),
		new("ACTOR_NPC_GARAGARA", "Marowak"),
		new("ACTOR_NPC_GIRATYINA", "Giratina"),
		new("ACTOR_NPC_GOORIKII", "Machoke"),
		new("ACTOR_NPC_GOOSUTO", "Haunter"),
		new("ACTOR_NPC_GOOSUTO2", "Haunter"),
		new("ACTOR_NPC_GOOSUTO3", "Haunter"),
		new("ACTOR_NPC_GOROON", "Graveler"),
		new("ACTOR_NPC_GURAADON", "Groudon"),
		new("ACTOR_NPC_GURAIGAA", "Gligar"),
		new("ACTOR_NPC_GUREGGURU", "Croagunk"),
		new("ACTOR_NPC_GYARADOSU", "Gyarados"),
		new("ACTOR_NPC_HASSAMU", "Scizor"),
		new("ACTOR_NPC_HEIGANI", "Corphish"),
		new("ACTOR_NPC_HERAKUROSU", "Heracross"),
		new("ACTOR_NPC_HERO_FIRST", "(Player)"),
		new("ACTOR_NPC_HERUGAA", "Houndoom"),
		new("ACTOR_NPC_HIIDORAN", "Heatran"),
		new("ACTOR_NPC_HIMEGUMA", "Teddiursa"),
		new("ACTOR_NPC_IRUMIIZE1", "Illumise"),
		new("ACTOR_NPC_IRUMIIZE2", "Illumise"),
		new("ACTOR_NPC_IRUMIIZE3", "Illumise"),
		new("ACTOR_NPC_IRUMIIZE4", "Illumise"),
		new("ACTOR_NPC_JIBAKOIRU", "Magnezone"),
		new("ACTOR_NPC_JIGUZAGUMA", "Zigzagoon"),
		new("ACTOR_NPC_JIRAACHI", "Jirachi"),
		new("ACTOR_NPC_JUPETTA", "Banette"),
		new("ACTOR_NPC_JUPUTORU", "Grovyle"),
		new("ACTOR_NPC_KABUTOPUSU", "Kabutops"),
		new("ACTOR_NPC_KAGEBOUZU", "Shuppet"),
		new("ACTOR_NPC_KAIOOGA", "Kyogre"),
		new("ACTOR_NPC_KAKUREON1", "Kecleon"),
		new("ACTOR_NPC_KAKUREON2", "Kecleon"),
		new("ACTOR_NPC_KEMUSSO", "Wurmple"),
		new("ACTOR_NPC_KIMAWARI", "Sunflora"),
		new("ACTOR_NPC_KINOGASSA", "Breloom"),
		new("ACTOR_NPC_KODORA", "Lairon"),
		new("ACTOR_NPC_KODORA2", "Lairon"),
		new("ACTOR_NPC_KODORA3", "Lairon"),
		new("ACTOR_NPC_KODORA4", "Lairon"),
		new("ACTOR_NPC_KODORA5", "Lairon"),
		new("ACTOR_NPC_KODORA6", "Lairon"),
		new("ACTOR_NPC_KOIRU", "Magnemite"),
		new("ACTOR_NPC_KOIRU2", "Magnemite"),
		new("ACTOR_NPC_KOOTASU", "Torkoal"),
		new("ACTOR_NPC_KUCHIITO", "Mawile"),
		new("ACTOR_NPC_KURABU", "Krabby"),
		new("ACTOR_NPC_KURESERIA", "Cresselia"),
		new("ACTOR_NPC_MAGUKARUGO", "Magcargo"),
		new("ACTOR_NPC_MAGUMAGGU", "Slugma"),
		new("ACTOR_NPC_MAGUMAGGU2", "Slugma"),
		new("ACTOR_NPC_MANAFI", "Manaphy"),
		new("ACTOR_NPC_MANKII", "Mankey"),
		new("ACTOR_NPC_MANMUU", "Mamoswine"),
		new("ACTOR_NPC_MANYUURA", "Weavile"),
		new("ACTOR_NPC_MARIRU", "Marill"),
		new("ACTOR_NPC_MASUKIPPA", "Carnivine"),
		new("ACTOR_NPC_MASUKIPPA2", "Carnivine"),
		new("ACTOR_NPC_MASUKIPPA3", "Carnivine"),
		new("ACTOR_NPC_MASUKIPPA4", "Carnivine"),
		new("ACTOR_NPC_MASUKIPPA5", "Carnivine"),
		new("ACTOR_NPC_METAMON", "Ditto"),
		new("ACTOR_NPC_METAMON_KIREIHANA", "Bellossom"),
		new("ACTOR_NPC_METAMON_OTACHI", "Sentret"),
		new("ACTOR_NPC_MIKARUGE", "Spiritomb"),
		new("ACTOR_NPC_MIMIROPPU", "Lopunny"),
		new("ACTOR_NPC_MUCHUURU", "Smoochum"),
		new("ACTOR_NPC_MUUMAAJI", "Mismagius"),
		new("ACTOR_NPC_MYUU", "Mew"),
		new("ACTOR_NPC_NEITYIO", "Xatu"),
		new("ACTOR_NPC_NIDOKINGU", "Nidoking"),
		new("ACTOR_NPC_NOKOTCHI", "Dunsparce"),
		new("ACTOR_NPC_NOKUTASU", "Cacturne"),
		new("ACTOR_NPC_NYOROTONO", "Politoed"),
		new("ACTOR_NPC_NYUURA", "Sneasel"),
		new("ACTOR_NPC_OKORIZARU", "Primeape"),
		new("ACTOR_NPC_OKUTAN", "Octillery"),
		new("ACTOR_NPC_OMUSUTAA", "Omastar"),
		new("ACTOR_NPC_OMUSUTAA2", "Omastar"),
		new("ACTOR_NPC_ONIGOORI", "Glalie"),
		new("ACTOR_NPC_ONIGOORI2", "Glalie"),
		new("ACTOR_NPC_ONIGOORI3", "Glalie"),
		new("ACTOR_NPC_ONIGOORI4", "Glalie"),
		new("ACTOR_NPC_OOSUBAME", "Swellow"),
		new("ACTOR_NPC_PACHIRISU", "Pachirisu"),
		new("ACTOR_NPC_PARTNER_FIRST", "(Partner)"),
		new("ACTOR_NPC_PARUKIA", "Palkia"),
		new("ACTOR_NPC_PATCHIIRU", "Spinda"),
		new("ACTOR_NPC_PERAPPU", "Chatot"),
		new("ACTOR_NPC_POPPO", "Pidgey"),
		new("ACTOR_NPC_PORIGON", "Porygon"),
		new("ACTOR_NPC_PORIGON2", "Porygon2"),
		new("ACTOR_NPC_PUKURIN", "Wigglytuff"),
		new("ACTOR_NPC_PUKURIN_MAMA", "Wigglytuff"),
		new("ACTOR_NPC_PUKURIN_PAPA", "Wigglytuff"),
		new("ACTOR_NPC_RAIBORUTO", "Manectric"),
		new("ACTOR_NPC_RAKURAI", "Electrike"),
		new("ACTOR_NPC_RAKURAI2", "Electrike"),
		new("ACTOR_NPC_RAKURAI3", "Electrike"),
		new("ACTOR_NPC_RAKURAI4", "Electrike"),
		new("ACTOR_NPC_RAKURAI5", "Electrike"),
		new("ACTOR_NPC_RAKURAI6", "Electrike"),
		new("ACTOR_NPC_RAKURAI7", "Electrike"),
		new("ACTOR_NPC_RAKURAI8", "Electrike"),
		new("ACTOR_NPC_RAPURASU", "Lapras"),
		new("ACTOR_NPC_REDIBA", "Ledyba"),
		new("ACTOR_NPC_REJIAISU", "Regice"),
		new("ACTOR_NPC_REJIGIGASU", "Regigigas"),
		new("ACTOR_NPC_REJIROKKU", "Regirock"),
		new("ACTOR_NPC_REJISUCHIRU", "Registeel"),
		new("ACTOR_NPC_REKKUUZA", "Rayquaza"),
		new("ACTOR_NPC_RINGUMA", "Ursaring"),
		new("ACTOR_NPC_RINGUMA2", "Ursaring"),
		new("ACTOR_NPC_RURIRI", "Azurill"),
		new("ACTOR_NPC_S_AGUNOMU", "Azelf"),
		new("ACTOR_NPC_S_BIPPA", "Bidoof"),
		new("ACTOR_NPC_S_CHIRIIN", "Chimecho"),
		new("ACTOR_NPC_S_DAGUTORIO", "Dugtrio"),
		new("ACTOR_NPC_S_DIGUDA", "Diglett"),
		new("ACTOR_NPC_S_DOGOOMU", "Loudred"),
		new("ACTOR_NPC_S_EMURITTO", "Mesprit"),
		new("ACTOR_NPC_S_HEIGANI", "Corphish"),
		new("ACTOR_NPC_S_JUPUTORU", "Grovyle"),
		new("ACTOR_NPC_S_KIMAWARI", "Sunflora"),
		new("ACTOR_NPC_S_PERAPPU", "Chatot"),
		new("ACTOR_NPC_S_PUKURIN", "Wigglytuff"),
		new("ACTOR_NPC_S_YAMIRAMI1", "Sableye"),
		new("ACTOR_NPC_S_YAMIRAMI2", "Sableye"),
		new("ACTOR_NPC_S_YONOWAARU", "Dusknoir"),
		new("ACTOR_NPC_S_YUKUSHII", "Uxie"),
		new("ACTOR_NPC_SAANAITO", "Gardevoir"),
		new("ACTOR_NPC_SANDOPAN", "Sandslash"),
		new("ACTOR_NPC_SEREBII", "Celebi"),
		new("ACTOR_NPC_SHADOW_DAAKURAI", "Shadow Darkrai"),
		new("ACTOR_NPC_SHEIMI", "Shaymin"),
		new("ACTOR_NPC_SHEIMI_FC", "Shaymin"),
		new("ACTOR_NPC_SOONANO", "Wynaut"),
		new("ACTOR_NPC_SOONANSU", "Wobbuffet"),
		new("ACTOR_NPC_SUBOMII", "Budew"),
		new("ACTOR_NPC_SUKATANKU", "Skuntank"),
		new("ACTOR_NPC_SUKORUPI", "Skorupi"),
		new("ACTOR_NPC_SURIIPU", "Drowzee"),
		new("ACTOR_NPC_SUTORAIKU", "Scyther"),
		new("ACTOR_NPC_TAMATAMA", "Exeggcute"),
		new("ACTOR_NPC_TANEBOO", "Seedot"),
		new("ACTOR_NPC_TATSUBEI", "Bagon"),
		new("ACTOR_NPC_TODOZERUGA", "Walrein"),
		new("ACTOR_NPC_TOGEPII", "Togepi"),
		new("ACTOR_NPC_UPAA", "Wooper"),
		new("ACTOR_NPC_YAMIKARASU", "Murkrow"),
		new("ACTOR_NPC_YAMIRAMI", "Sableye"),
		new("ACTOR_NPC_YAMIRAMI2", "Sableye"),
		new("ACTOR_NPC_YAMIRAMI3", "Sableye"),
		new("ACTOR_NPC_YAMIRAMI4", "Sableye"),
		new("ACTOR_NPC_YAMIRAMI5", "Sableye"),
		new("ACTOR_NPC_YAMIRAMI6", "Sableye"),
		new("ACTOR_NPC_YARUKIMONO", "Vigoroth"),
		new("ACTOR_NPC_YONOWAARU", "Dusknoir"),
		new("ACTOR_NPC_YONOWAARU_N8", "Dusknoir"),
		new("ACTOR_NPC_YONOWAARU_N9", "Dusknoir"),
		new("ACTOR_NPC_YUKIKABURI", "Snover"),
		new("ACTOR_NPC_YUKIMENOKO", "Froslass"),
		new("ACTOR_NPC_YUKIWARASHI", "Snorunt"),
		new("ACTOR_NPC_YUKIWARASHI2", "Snorunt"),
		new("ACTOR_NPC_YUKIWARASHI3", "Snorunt"),
		new("ACTOR_NPC_YUKIWARASHI4", "Snorunt"),
		new("ACTOR_NPC_YUKUSHII", "Uxie"),
		new("ACTOR_NPC_ZANGUUSU", "Zangoose"),
		new("ACTOR_NPC_ZUBATTO", "Zubat"),
		new("ACTOR_PLAYER_BIPPA", "Bidoof"),
		new("ACTOR_PLAYER_CHARMS", "Lopunny"),
		new("ACTOR_PLAYER_FUTURE", "Grovyle"),
		new("ACTOR_PLAYER_KIMAWARI", "Sunflora"),
		new("ACTOR_PLAYER_PUPURIN", "Igglybuff"),
	]);

	public static Dictionary<string, string> effects = new([
		new("EFFECT_NONE",""),
		new("EFFECT_EXCLAMATION_MARK","❗"),
		new("EFFECT_SHOCKED","〽"),
		new("EFFECT_SHOCKED_MIRRORED","〽"),
		new("EFFECT_SWEAT_DROP","💧"),
		new("EFFECT_SWEAT_DROP_SLOW","💧"),
		new("EFFECT_SWEAT_DROPS_FROM_BOTH_SIDES_MEDIUM","💦"),
		new("EFFECT_QUESTION_MARK","❓"),
		new("EFFECT_ANGRY","💢"),
		new("EFFECT_ANGRY_MIRRORED","💢"),
		new("EFFECT_TWO_ARROWS_AT_SIDE_LEFT","⚟"),
		new("EFFECT_TWO_ARROWS_AT_SIDE_RIGHT","⚞"),
		new("EFFECT_LAUGHING","🔆"),
		new("EFFECT_JOYOUS","◀▼▶"),
		new("EFFECT_VERY_HEAVY_RAIN","⛈️"),
		new("EFFECT_CONFETTI","🎊"),
		new("EFFECT_STUCK_IN_YELLOW_WATER","🕳️"),
		new("EFFECT_STUCK_IN_YELLOW_WATER2","🕳️"),
		new("EFFECT_STUCK_IN_YELLOW_WATER_DEEP","🕳️"),
		new("EFFECT_STUCK_IN_YELLOW_WATER_DEEP2","🕳️"),
		new("EFFECT_STUCK_IN_YELLOW_WATER_DEEP_MEDIUM","🕳️"),
		new("EFFECT_STUCK_IN_YELLOW_WATER_DEEP_MEDIUM2","🕳️"),
		new("EFFECT_STUCK_IN_YELLOW_WATER_MEDIUM","🕳️"),
		new("EFFECT_STUCK_IN_YELLOW_WATER_MEDIUM2","🕳️"),
		new("EFFECT_EATING","🍴"),
		new("EFFECT_EATING_SLOW","🍴"),
		new("EFFECT_APPLE_ON_HEAD","🍎"),
		new("EFFECT_LIGHT_ENGULFING","🟡"),
		new("EFFECT_LIGHT_ENGULFING2","🟡"),
		new("EFFECT_LIGHT_EXPLOSION","💥"),
		new("EFFECT_LIGHT_EXPLOSION_LIGHTNING","⚡"),
		new("EFFECT_LIGHT_END_ENGULFING","🟡"),
		new("EFFECT_WHITE_LIGHT_ENGULFING_OUT","⚪"),
		new("EFFECT_WHITE_LIGHT_ENGULFING_IN","⚪"),
		new("EFFECT_WHITE_LIGHT_ENGULFING","⚪"),
		new("EFFECT_ROCKS_HITTING","🪨"),
		new("EFFECT_SMOKE_PUFF_SMALL","💨"),
		new("EFFECT_SMOKE_PUFF","☁️")
	]);

	public static Dictionary<string, string> faces = new([
		new("FACE_ANGRY", "Angry"),
		new("FACE_CRYING", "Crying"),
		new("FACE_DETERMINED", "Determined"),
		new("FACE_DIZZY", "Dizzy"),
		new("FACE_HAPPY", "Happy"),
		new("FACE_INSPIRED", "Inspired"),
		new("FACE_JOYOUS", "Joyous"),
		new("FACE_NORMAL", "Normal"),
		new("FACE_PAIN", "Pain"),
		new("FACE_SAD", "Sad"),
		new("FACE_SHOUTING", "Shouting"),
		new("FACE_SIGH", "Sigh"),
		new("FACE_SPECIAL2", "Special2"),
		new("FACE_STUNNED", "Stunned"),
		new("FACE_SURPRISED", "Surprised"),
		new("FACE_TEARY_EYED", "Teary-Eyed"),
		new("FACE_WORRIED", "Worried")
	]);

	public static int AnimationSum = 0;
	public static int ArgumentSum = 0;
	public static int ArrayAccessorSum = 0;
	public static int ConditionalSum = 0;
	public static int DialogueSum = 0;
	public static int IdentifierSum = 0;
	public static int LabelSum = 0;
	public static int NodeSum = 0;
	public static int SwitchSum = 0;
	public static int TemplateSum = 0;
	public static int TokenSum = 0;

	public static List<string> Identifiers = [];

	public static void Concurrent(Action callback) => Application.Current.Dispatcher.Invoke(callback);

	public static T Concurrent<T>(Func<T> callback) => Application.Current.Dispatcher.Invoke(callback);
}