using System.Globalization;

namespace ES2MD;

/// <summary>
/// Plaintext translations of variables, dialogue tags, and more.
/// </summary>
static class Localization
{
	public static Dictionary<string, string> actors = new([
		new("ACTOR_ADVENTURE_NPC1", "(__NPC1)"),
		new("ACTOR_ADVENTURE_NPC2", "(__NPC2)"),
		new("ACTOR_ADVENTURE_NPC3", "(__NPC3)"),
		new("ACTOR_ATTENDANT_MANAFI", "Manaphy"),
		new("ACTOR_ATTENDANT1", "Partner Name"),
		new("ACTOR_ATTENDANT2", "Manaphy"),
		new("ACTOR_NPC_AABOKKU", "Arbok"),
		new("ACTOR_NPC_AAMARUDO", "Armaldo"),
		new("ACTOR_NPC_AGUNOMU", "Azelf"),
		new("ACTOR_NPC_BANEBUU", "Spoink"),
		new("ACTOR_NPC_BARIYAADO", "Mr. Mime"),
		new("ACTOR_NPC_BARUBIITO1", "Volbeat"),
		new("ACTOR_NPC_BARUBIITO2", "Volbeat"),
		new("ACTOR_NPC_BARUBIITO3", "Volbeat"),
		new("ACTOR_NPC_BARUBIITO4", "Volbeat"),
		new("ACTOR_NPC_BETOBETAA", "Grimer"),
		new("ACTOR_NPC_BETOBETAA2", "Volbeat"),
		new("ACTOR_NPC_BETOBETAA3", "Volbeat"),
		new("ACTOR_NPC_BETOBETAA4", "Volbeat"),
		new("ACTOR_NPC_BETOBETAA5", "Volbeat"),
		new("ACTOR_NPC_BETOBETON", "Muk"),
		new("ACTOR_NPC_BETOBETON2", "Muk"),
		new("ACTOR_NPC_BETOBETON3", "Muk"),
		new("ACTOR_NPC_BIIDARU", "Bibarel"),
		new("ACTOR_NPC_BIPPA", "Bidoof"),
		new("ACTOR_NPC_BIPPA_BRO", "Bidoof"),
		new("ACTOR_NPC_BIPPA_SIS", "Bidoof"),
		new("ACTOR_NPC_BOSUGODORA", "Aggron"),
		new("ACTOR_NPC_BUUBAAN", "Magmortar"),
		new("ACTOR_NPC_CHAAREMU", "Medicham"),
		new("ACTOR_NPC_CHIRIIN", "Chimecho"),
		new("ACTOR_NPC_DAAKURAI", "Darkrai"),
		new("ACTOR_NPC_DAGUTORIO", "Dugtrio"),
		new("ACTOR_NPC_DARK_DIARUGA", "Primal Dialga"),
		new("ACTOR_NPC_DARK_PUKURIN", "Primal Wigglytuff"),
		new("ACTOR_NPC_DEBUG", "(Debug)"),
		new("ACTOR_NPC_DENRYUU", "Ampharos"),
		new("ACTOR_NPC_DIARUGA", "Dialga"),
		new("ACTOR_NPC_DIGUDA", "Diglett"),
		new("ACTOR_NPC_DOGAASU", "Koffing"),
		new("ACTOR_NPC_DOGOOMU", "Loudred"),
		new("ACTOR_NPC_DORAPION", "Drapion"),
		new("ACTOR_NPC_DOSAIDON", "Rhyperior"),
		new("ACTOR_NPC_EMURITTO", "Mesprit"),
		new("ACTOR_NPC_FIONE1", "Phione"),
		new("ACTOR_NPC_FIONE2", "Phione"),
		new("ACTOR_NPC_FIONE3", "Phione"),
		new("ACTOR_NPC_FIONE4", "Phione"),
		new("ACTOR_NPC_FIONE5", "Phione"),
		new("ACTOR_NPC_FIONE6", "Phione"),
		new("ACTOR_NPC_FIONE7", "Phione"),
		new("ACTOR_NPC_FIONE8", "Phione"),
		new("ACTOR_NPC_FURIIZAA", "Articuno"),
		new("ACTOR_NPC_GARAGARA", "Marowak"),
		new("ACTOR_NPC_GIRATYINA", "Giratina"),
		new("ACTOR_NPC_GOORIKII", "Machoke"),
		new("ACTOR_NPC_GOOSUTO", "Haunter"),
		new("ACTOR_NPC_GOOSUTO2", "Haunter"),
		new("ACTOR_NPC_GOOSUTO3", "Haunter"),
		new("ACTOR_NPC_GOROON", "Graveler"),
		new("ACTOR_NPC_GURAADON", "Groudon"),
		new("ACTOR_NPC_GURAIGAA", "Gligar"),
		new("ACTOR_NPC_GUREGGURU", "Croagunk"),
		new("ACTOR_NPC_GYARADOSU", "Gyarados"),
		new("ACTOR_NPC_HASSAMU", "Scizor"),
		new("ACTOR_NPC_HEIGANI", "Corphish"),
		new("ACTOR_NPC_HERAKUROSU", "Heracross"),
		new("ACTOR_NPC_HERO_FIRST", "Hero Name"),
		new("ACTOR_NPC_HERUGAA", "Houndoom"),
		new("ACTOR_NPC_HIIDORAN", "Heatran"),
		new("ACTOR_NPC_HIMEGUMA", "Teddiursa"),
		new("ACTOR_NPC_IRUMIIZE1", "Illumise"),
		new("ACTOR_NPC_IRUMIIZE2", "Illumise"),
		new("ACTOR_NPC_IRUMIIZE3", "Illumise"),
		new("ACTOR_NPC_IRUMIIZE4", "Illumise"),
		new("ACTOR_NPC_JIBAKOIRU", "Magnezone"),
		new("ACTOR_NPC_JIGUZAGUMA", "Zigzagoon"),
		new("ACTOR_NPC_JIRAACHI", "Jirachi"),
		new("ACTOR_NPC_JUPETTA", "Banette"),
		new("ACTOR_NPC_JUPUTORU", "Grovyle"),
		new("ACTOR_NPC_KABUTOPUSU", "Kabutops"),
		new("ACTOR_NPC_KAGEBOUZU", "Shuppet"),
		new("ACTOR_NPC_KAIOOGA", "Kyogre"),
		new("ACTOR_NPC_KAKUREON1", "Kecleon"),
		new("ACTOR_NPC_KAKUREON2", "Kecleon"),
		new("ACTOR_NPC_KEMUSSO", "Wurmple"),
		new("ACTOR_NPC_KIMAWARI", "Sunflora"),
		new("ACTOR_NPC_KINOGASSA", "Breloom"),
		new("ACTOR_NPC_KODORA", "Lairon"),
		new("ACTOR_NPC_KODORA2", "Lairon"),
		new("ACTOR_NPC_KODORA3", "Lairon"),
		new("ACTOR_NPC_KODORA4", "Lairon"),
		new("ACTOR_NPC_KODORA5", "Lairon"),
		new("ACTOR_NPC_KODORA6", "Lairon"),
		new("ACTOR_NPC_KOIRU", "Magnemite"),
		new("ACTOR_NPC_KOIRU2", "Magnemite"),
		new("ACTOR_NPC_KOOTASU", "Torkoal"),
		new("ACTOR_NPC_KUCHIITO", "Mawile"),
		new("ACTOR_NPC_KURABU", "Krabby"),
		new("ACTOR_NPC_KURESERIA", "Cresselia"),
		new("ACTOR_NPC_MAGUKARUGO", "Magcargo"),
		new("ACTOR_NPC_MAGUMAGGU", "Slugma"),
		new("ACTOR_NPC_MAGUMAGGU2", "Slugma"),
		new("ACTOR_NPC_MANAFI", "Manaphy"),
		new("ACTOR_NPC_MANKII", "Mankey"),
		new("ACTOR_NPC_MANMUU", "Mamoswine"),
		new("ACTOR_NPC_MANYUURA", "Weavile"),
		new("ACTOR_NPC_MARIRU", "Marill"),
		new("ACTOR_NPC_MASUKIPPA", "Carnivine"),
		new("ACTOR_NPC_MASUKIPPA2", "Carnivine"),
		new("ACTOR_NPC_MASUKIPPA3", "Carnivine"),
		new("ACTOR_NPC_MASUKIPPA4", "Carnivine"),
		new("ACTOR_NPC_MASUKIPPA5", "Carnivine"),
		new("ACTOR_NPC_METAMON", "Ditto"),
		new("ACTOR_NPC_METAMON_KIREIHANA", "Bellossom"),
		new("ACTOR_NPC_METAMON_OTACHI", "Sentret"),
		new("ACTOR_NPC_MIKARUGE", "Spiritomb"),
		new("ACTOR_NPC_MIMIROPPU", "Lopunny"),
		new("ACTOR_NPC_MUCHUURU", "Smoochum"),
		new("ACTOR_NPC_MUUMAAJI", "Mismagius"),
		new("ACTOR_NPC_MYUU", "Mew"),
		new("ACTOR_NPC_NEITYIO", "Xatu"),
		new("ACTOR_NPC_NIDOKINGU", "Nidoking"),
		new("ACTOR_NPC_NOKOTCHI", "Dunsparce"),
		new("ACTOR_NPC_NOKUTASU", "Cacturne"),
		new("ACTOR_NPC_NYOROTONO", "Politoed"),
		new("ACTOR_NPC_NYUURA", "Sneasel"),
		new("ACTOR_NPC_OKORIZARU", "Primeape"),
		new("ACTOR_NPC_OKUTAN", "Octillery"),
		new("ACTOR_NPC_OMUSUTAA", "Omastar"),
		new("ACTOR_NPC_OMUSUTAA2", "Omastar"),
		new("ACTOR_NPC_ONIGOORI", "Glalie"),
		new("ACTOR_NPC_ONIGOORI2", "Glalie"),
		new("ACTOR_NPC_ONIGOORI3", "Glalie"),
		new("ACTOR_NPC_ONIGOORI4", "Glalie"),
		new("ACTOR_NPC_OOSUBAME", "Swellow"),
		new("ACTOR_NPC_PACHIRISU", "Pachirisu"),
		new("ACTOR_NPC_PARTNER_FIRST", "Partner Name"),
		new("ACTOR_NPC_PARUKIA", "Palkia"),
		new("ACTOR_NPC_PATCHIIRU", "Spinda"),
		new("ACTOR_NPC_PERAPPU", "Chatot"),
		new("ACTOR_NPC_POPPO", "Pidgey"),
		new("ACTOR_NPC_PORIGON", "Porygon"),
		new("ACTOR_NPC_PORIGON2", "Porygon2"),
		new("ACTOR_NPC_PUKURIN", "Wigglytuff"),
		new("ACTOR_NPC_PUKURIN_MAMA", "Wigglytuff"),
		new("ACTOR_NPC_PUKURIN_PAPA", "Wigglytuff"),
		new("ACTOR_NPC_RAIBORUTO", "Manectric"),
		new("ACTOR_NPC_RAKURAI", "Electrike"),
		new("ACTOR_NPC_RAKURAI2", "Electrike"),
		new("ACTOR_NPC_RAKURAI3", "Electrike"),
		new("ACTOR_NPC_RAKURAI4", "Electrike"),
		new("ACTOR_NPC_RAKURAI5", "Electrike"),
		new("ACTOR_NPC_RAKURAI6", "Electrike"),
		new("ACTOR_NPC_RAKURAI7", "Electrike"),
		new("ACTOR_NPC_RAKURAI8", "Electrike"),
		new("ACTOR_NPC_RAPURASU", "Lapras"),
		new("ACTOR_NPC_REDIBA", "Ledyba"),
		new("ACTOR_NPC_REJIAISU", "Regice"),
		new("ACTOR_NPC_REJIGIGASU", "Regigigas"),
		new("ACTOR_NPC_REJIROKKU", "Regirock"),
		new("ACTOR_NPC_REJISUCHIRU", "Registeel"),
		new("ACTOR_NPC_REKKUUZA", "Rayquaza"),
		new("ACTOR_NPC_RINGUMA", "Ursaring"),
		new("ACTOR_NPC_RINGUMA2", "Ursaring"),
		new("ACTOR_NPC_RURIRI", "Azurill"),
		new("ACTOR_NPC_S_AGUNOMU", "Azelf"),
		new("ACTOR_NPC_S_BIPPA", "Bidoof"),
		new("ACTOR_NPC_S_CHIRIIN", "Chimecho"),
		new("ACTOR_NPC_S_DAGUTORIO", "Dugtrio"),
		new("ACTOR_NPC_S_DIGUDA", "Diglett"),
		new("ACTOR_NPC_S_DOGOOMU", "Loudred"),
		new("ACTOR_NPC_S_EMURITTO", "Mesprit"),
		new("ACTOR_NPC_S_HEIGANI", "Corphish"),
		new("ACTOR_NPC_S_JUPUTORU", "Grovyle"),
		new("ACTOR_NPC_S_KIMAWARI", "Sunflora"),
		new("ACTOR_NPC_S_PERAPPU", "Chatot"),
		new("ACTOR_NPC_S_PUKURIN", "Wigglytuff"),
		new("ACTOR_NPC_S_YAMIRAMI1", "Sableye"),
		new("ACTOR_NPC_S_YAMIRAMI2", "Sableye"),
		new("ACTOR_NPC_S_YONOWAARU", "Dusknoir"),
		new("ACTOR_NPC_S_YUKUSHII", "Uxie"),
		new("ACTOR_NPC_SAANAITO", "Gardevoir"),
		new("ACTOR_NPC_SANDOPAN", "Sandslash"),
		new("ACTOR_NPC_SEREBII", "Celebi"),
		new("ACTOR_NPC_SHADOW_DAAKURAI", "Shadow Darkrai"),
		new("ACTOR_NPC_SHEIMI", "Shaymin"),
		new("ACTOR_NPC_SHEIMI_FC", "Shaymin"),
		new("ACTOR_NPC_SOONANO", "Wynaut"),
		new("ACTOR_NPC_SOONANSU", "Wobbuffet"),
		new("ACTOR_NPC_SUBOMII", "Budew"),
		new("ACTOR_NPC_SUKATANKU", "Skuntank"),
		new("ACTOR_NPC_SUKORUPI", "Skorupi"),
		new("ACTOR_NPC_SURIIPU", "Drowzee"),
		new("ACTOR_NPC_SUTORAIKU", "Scyther"),
		new("ACTOR_NPC_TAMATAMA", "Exeggcute"),
		new("ACTOR_NPC_TANEBOO", "Seedot"),
		new("ACTOR_NPC_TATSUBEI", "Bagon"),
		new("ACTOR_NPC_TODOZERUGA", "Walrein"),
		new("ACTOR_NPC_TOGEPII", "Togepi"),
		new("ACTOR_NPC_UPAA", "Wooper"),
		new("ACTOR_NPC_YAMIKARASU", "Murkrow"),
		new("ACTOR_NPC_YAMIRAMI", "Sableye"),
		new("ACTOR_NPC_YAMIRAMI2", "Sableye"),
		new("ACTOR_NPC_YAMIRAMI3", "Sableye"),
		new("ACTOR_NPC_YAMIRAMI4", "Sableye"),
		new("ACTOR_NPC_YAMIRAMI5", "Sableye"),
		new("ACTOR_NPC_YAMIRAMI6", "Sableye"),
		new("ACTOR_NPC_YARUKIMONO", "Vigoroth"),
		new("ACTOR_NPC_YONOWAARU", "Dusknoir"),
		new("ACTOR_NPC_YONOWAARU_N8", "Dusknoir"),
		new("ACTOR_NPC_YONOWAARU_N9", "Dusknoir"),
		new("ACTOR_NPC_YUKIKABURI", "Snover"),
		new("ACTOR_NPC_YUKIMENOKO", "Froslass"),
		new("ACTOR_NPC_YUKIWARASHI", "Snorunt"),
		new("ACTOR_NPC_YUKIWARASHI2", "Snorunt"),
		new("ACTOR_NPC_YUKIWARASHI3", "Snorunt"),
		new("ACTOR_NPC_YUKIWARASHI4", "Snorunt"),
		new("ACTOR_NPC_YUKUSHII", "Uxie"),
		new("ACTOR_NPC_ZANGUUSU", "Zangoose"),
		new("ACTOR_NPC_ZUBATTO", "Zubat"),
		new("ACTOR_PLAYER", "Hero Name"),
		new("ACTOR_PLAYER_BIPPA", "Bidoof"),
		new("ACTOR_PLAYER_CHARMS", "Lopunny"),
		new("ACTOR_PLAYER_FUTURE", "Grovyle"),
		new("ACTOR_PLAYER_KIMAWARI", "Sunflora"),
		new("ACTOR_PLAYER_PUPURIN", "Igglybuff"),
]);

	public static Dictionary<string, string> effects = new([
		new("EFFECT_EXCLAMATION_MARK","❗"),
		new("EFFECT_SHOCKED","〽"),
		new("EFFECT_SHOCKED_MIRRORED","〽"),
		new("EFFECT_SWEAT_DROP","💧"),
		new("EFFECT_SWEAT_DROP_SLOW","💧"),
		new("EFFECT_SWEAT_DROPS_FROM_BOTH_SIDES_MEDIUM","💦"),
		new("EFFECT_QUESTION_MARK","❓"),
		new("EFFECT_ANGRY","💢"),
		new("EFFECT_ANGRY_MIRRORED","💢"),
		new("EFFECT_TWO_ARROWS_AT_SIDE_LEFT","⚟"),
		new("EFFECT_TWO_ARROWS_AT_SIDE_RIGHT","⚞"),
		new("EFFECT_LAUGHING","🔆"),
		new("EFFECT_JOYOUS","◀▼▶"),
		new("EFFECT_VERY_HEAVY_RAIN","⛈️"),
		new("EFFECT_CONFETTI","🎊"),
		new("EFFECT_STUCK_IN_YELLOW_WATER","🕳️"),
		new("EFFECT_STUCK_IN_YELLOW_WATER2","🕳️"),
		new("EFFECT_STUCK_IN_YELLOW_WATER_DEEP","🕳️"),
		new("EFFECT_STUCK_IN_YELLOW_WATER_DEEP2","🕳️"),
		new("EFFECT_STUCK_IN_YELLOW_WATER_DEEP_MEDIUM","🕳️"),
		new("EFFECT_STUCK_IN_YELLOW_WATER_DEEP_MEDIUM2","🕳️"),
		new("EFFECT_STUCK_IN_YELLOW_WATER_MEDIUM","🕳️"),
		new("EFFECT_STUCK_IN_YELLOW_WATER_MEDIUM2","🕳️"),
		new("EFFECT_EATING","🍴"),
		new("EFFECT_EATING_SLOW","🍴"),
		new("EFFECT_APPLE_ON_HEAD","🍎"),
		new("EFFECT_LIGHT_ENGULFING","🟡"),
		new("EFFECT_LIGHT_ENGULFING2","🟡"),
		new("EFFECT_LIGHT_EXPLOSION","💥"),
		new("EFFECT_LIGHT_EXPLOSION_LIGHTNING","⚡"),
		new("EFFECT_LIGHT_END_ENGULFING","🟡"),
		new("EFFECT_WHITE_LIGHT_ENGULFING_OUT","⚪"),
		new("EFFECT_WHITE_LIGHT_ENGULFING_IN","⚪"),
		new("EFFECT_WHITE_LIGHT_ENGULFING","⚪"),
		new("EFFECT_ROCKS_HITTING","🪨"),
		new("EFFECT_SMOKE_PUFF_SMALL","💨"),
		new("EFFECT_SMOKE_PUFF","☁️")
	]);

	public static Dictionary<string, string> faces = new([
		new("FACE_ANGRY", "Angry"),
		new("FACE_CRYING", "Crying"),
		new("FACE_DETERMINED", "Determined"),
		new("FACE_DIZZY", "Dizzy"),
		new("FACE_HAPPY", "Happy"),
		new("FACE_INSPIRED", "Inspired"),
		new("FACE_JOYOUS", "Joyous"),
		new("FACE_NORMAL", "Normal"),
		new("FACE_PAIN", "Pain"),
		new("FACE_SAD", "Sad"),
		new("FACE_SHOUTING", "Shouting"),
		new("FACE_SIGH", "Sigh"),
		new("FACE_SPECIAL2", "Special2"),
		new("FACE_STUNNED", "Stunned"),
		new("FACE_SURPRISED", "Surprised"),
		new("FACE_TEARY_EYED", "Teary-Eyed"),
		new("FACE_WORRIED", "Worried")
	]);

	public static Dictionary<string, string> mapIDs = new ([
		new("23", "Craggy Coast"),
		new("24", "Rock Path"),
		new("25", "Foggy Forest"),
		new("26", "Rock Path"),
		new("27", "Mt. Horn"),
		new("45", "Sealed Ruin"),
		new("46", "Deep Sealed Ruin"),
		new("47", "Dusk Forest"),
		new("48", "Deep Dusk Forest"),
		new("50", "Treeshroud Forest"),
		new("51", "Treeshroud Forest after previously failing"),
		new("52", "Deep Treeshroud Forest"),
		new("55", "Brine Cave"),
		new("56", "Lower Brine Cave"),
		new("59", "Hidden Land"),
		new("60", "Hidden Highland"),
		new("67", "Temporal Tower"),
		new("68", "Temporal Spire"),
		new("74", "Mystifying Forest"),
		new("97", "Spacial Rift"),
		new("98", "Deep Spacial Rift"),
		new("102", "Dark Crater"),
		new("156", "Shaymin Village"),
		new("228", "Hot Spring"),
		new("311", "the Beach"),
	]);

	public static Dictionary<string, string> scenarioFlags = new([
		new("[3, 1]", "the Hero and Partner have arrived at Wigglytuff's Guild"),
		new("[3, 3]", "the team has arrived at Drenched Bluff"),
		new("[4, 0]", "the team has slept at the Guild for the first time"),
		new("[4, 1]", "Chatot has spotted the team wandering around"),
		new("[4, 2]", "the team has met Marill and Azurill"),
		new("[4, 3]", "the team has met Drowzee"),
		new("[4, 5]", "the team has reached the foot of Mt. Bristle"),
		new("[4, 7]", "the team has rescued Azurill"),
		new("[5, 2]", "the team has started sentry duty"),
		new("[6, 1]", "the team has been informed of a Time Gear theft"),
		new("[6, 5]", "the team has reached the other side of the waterfall"),
		new("[7, 0]", "the team has learned about the expedition"),
		new("[7, 1]", "the Guild has learned about the expedition"),
		new("[7, 2]", "the team has spotted Team Skull at the notice boards"),
		new("[7, 5]", "the team has started their second round of sentry duty"),
		new("[7, 6]", "Chatot has introduced Team Skull to the Guild"),
		new("[8, 1]", "Chatot has asked the team to get Perfect Apples"),
		new("[8, 2]", "the team has entered Apple Woods"),
		new("[8, 3]", "Team Skull has stolen the Perfect Apples"),
		new("[9, 1]", "The expedition members have been announced"),
		new("[9, 5]", "the first leg of the expedition has begun"),
		new("[10, 2]", "the second leg of the expedition has begun"),
		new("[11, 1]", "the team has arrived at Steam Cave"),
		new("[11, 2]", "Team Skull has attacked Wigglytuff"),
		new("[11, 3]", "the team has arrived at Upper Steam Cave"),
		new("[11, 4]", "the Hero has realized they've visited Fogbound Lake as a human"),
		new("[12, 0]", "the expedition has concluded"),
		new("[12, 1]", "Dusknoir has arrived at the Guild"),
		new("[12, 3]", "Chatot has sent the team to Kecleon Market for Perfect Apples"),
		new("[12, 4]", "Dusknoir has met the team at Kecleon Market"),
		new("[13, 0]", "the third Time Gear has been stolen"),
		new("[13, 1]", "Loudred has told the team they have visitors"),
		new("[13, 2]", "the team has entered Amp Plains"),
		new("[13, 3]", "the team has entered Far Amp Plains"),
		new("[14, 1]", "the team has been informed of the Fogbound Lake Time Gear theft"),
		new("[14, 2]", "the team has been assigned to search for Grovyle"),
		new("[14, 4]", "the team has entered Northern Desert"),
		new("[14, 5]", "the team has discovered quicksand pits in the desert"),
		new("[15, 1]", "the Hero has decided to jump into the quicksand pits"),
		new("[15, 2]", "the team has jumped into the quicksand pits"),
		new("[15, 4]", "the Guild has set out for Crystal Cave"),
		new("[16, 1]", "the team has entered Crystal Cave"),
		new("[16, 2]", "the team has arrived at the depths of Crystal Cave"),
		new("[17, 1]", "Chapter 13 has begun"),
		new("[17, 2]", "Dusknoir has revealed himself to be from the future"),
		new("[17, 3]", "Chatot has said there's no news on Grovyle"),
		new("[17, 4]", "the team has discussed Azelf's state since the loss of the Time Gear"),
		new("[18, 1]", "the Hero has begun fading in and out of consciousness"),
		new("[18, 2]", "the Hero has tried to open the cell doors"),
		new("[19, 2]", "the team has observed the lights of the stockade in the distance"),
		new("[19, 3]", "the team has entered Sealed Ruin Pit"),
		new("[20, 1]", "Chapter 15 has begun"),
		new("[20, 2]", "the team has entered Dusk Forest"),
		new("[21, 1]", "the team and Grovyle have returned to the present"),
		new("[22, 1]", "the team has returned to the Guild"),
		new("[22, 2]", "Chatot has given the Guild their orders on the Hidden Land"),
		new("[22, 3]", "the Guild has given their update on finding the Hidden Land"),
		new("[23, 0]", "the team has spoken with Torkoal"),
		new("[23, 1]", "Torkoal has arrived at the sentry grate"),
		new("[23, 2]", "Team Skull has ambushed Torkoal"),
		new("[23, 3]", "the Partner has wondered if Torkoal has returned"),
		new("[24, 0]", "Lapras has spoken to Wigglytuff"),
		new("[24, 1]", "the Guild has prepared to leave for Brine Cave"),
		new("[24, 2]", "Team Skull has stolen the relic fragment a second time"),
		new("[25, 2]", "the team has entered the Hidden Land"),
		new("[25, 3]", "the team has entered the Hidden Highland"),
		new("[25, 4]", "the team has arrived at the Rainbow Stoneship"),
		new("= 26", "the team has ridden on the Rainbow Stoneship"),
		new("[26, 3]", "the team has arrived at Temporal Tower"),
		new("[26, 4]", "the team has arrived at Temporal Spire"),
		new("[26, 5]", "the team has entered Temporal Spire"),
		new("[29, 1]", "Chatot has announced the Graduation Exam"),
		new("[29, 2]", "the team has run into Teddiursa and Ursaring"),
		new("[29, 3]", "the team has entered Mystifying Forest"),
		new("[29, 4]", "the team has fallen into a pit trap in Mystifying Forest"),
		new("[29, 5]", "the team has passed the Graduation Exam"),
		new("[29, 8]", "the team has learned there's happy news out of the café"),
		new("[29, 10]", "the team has arrived at Shaymin Village"),
		new("[29, 11]", "the team has returned to Treasure Town from Shaymin Village"),
		new("[29, 12]", "the team has reached Sky Peak's 1st Station Clearing"),
		new("[29, 13]", "the team has returned to Shaymin Village from the 1st Station Clearing"),
		new("[29, 14]", "the team has reached Sky Peak's 2nd Station Clearing"),
		new("[29, 15]", "the team has returned to Shaymin Village from the 2nd Station Clearing"),
		new("[29, 16]", "the team has reached Sky Peak's 3rd Station Clearing"),
		new("[29, 17]", "the team has returned to Shaymin Village from the 3rd Station Clearing"),
		new("[29, 18]", "the team has reached Sky Peak's 4th Station Clearing"),
		new("[29, 19]", "the team has returned to Shaymin Village from the 4th Station Clearing"),
		new("[29, 20]", "the team has reached Sky Peak's 5th Station Clearing"),
		new("[29, 21]", "the team has returned to Shaymin Village from the 5th Station Clearing"),
		new("[29, 22]", "the team has reached Sky Peak's 6th Station Clearing"),
		new("[29, 23]", "the team has returned to Shaymin Village from the 6th Station Clearing"),
		new("[29, 24]", "the team has reached Sky Peak's 7th Station Clearing"),
		new("[29, 25]", "the team has returned to Shaymin Village from the 7th Station Clearing"),
		new("[29, 26]", "the team has reached Sky Peak's 8th Station Clearing and asked Ampharos for help"),
		new("[29, 27]", "the team has returned to Shaymin Village from the 8th Station Clearing"),
		new("[29, 28]", "the team has reached Sky Peak's 9th Station Clearing"),
		new("[29, 29]", "the team has returned to Shaymin Village from the 9th Station Clearing"),
		new("[29, 30]", "the team has reached the summit of Sky Peak"),
		new("[29, 31]", "Shaymin has defeated the Grimer and Muk on Sky Peak"),
		new("[29, 33]", "the team has spoken to Mr. Mime and learned about Scizor"),
		new("[29, 39]", "Scizor has granted the team the Secret Rank"),
		new("[29, 41]", "Sunflora has told the team about the Surround Sea"),
		new("[29, 42]", "Manaphy has hatched from its egg"),
		new("[29, 43]", "the Partner has suggested giving Manaphy a Blue Gummi"),
		new("[29, 44]", "the Hero has fed Manaphy a Blue Gummi"),
		new("[29, 45]", "the Partner has suggested giving Manaphy a second Blue Gummi"),
		new("[29, 46]", "the Hero has fed Manaphy a second Blue Gummi"),
		new("[29, 47]", "the team has played with Manaphy at the beach"),
		new("[29, 48]", "Chatot has joined the search for Manaphy"),
		new("[29, 49]", "Manaphy has fainted on the beach"),
		new("[29, 52]", "Phione has given the team the Phione Dew"),
		new("[29, 55]", "Team Charm has arrived at the Guild"),
		new("[29, 59]", "the team has encountered Regice"),
		new("[29, 62]", "the team has encountered Regirock"),
		new("[29, 64]", "the team has encountered Registeel"),
		new("[29, 67]", "the team has unlocked Concealed Ruins"),
		new("[29, 69]", "Epilogue 7 has begun"),
		new("[29, 72]", "the team has found Azurill trapped in a nightmare"),
		new("[29, 75]", "the team has found Drowzee and asked for his help with Azurill's nightmare"),
		new("[29, 76]", "the team has entered Azurill's nightmare"),
		new("[29, 78]", "the team has informed the Guild of Cresselia's involvement in the spreading nightmares"),
		new("[29, 80]", "Lapras has told the team about Palkia"),
		new("[29, 81]", "the team has fallen to the bottom of Spacial Rift"),
		new("[29, 82]", "the team has been defeated in Spacial Rift"),
		new("[29, 84]", "the team has entered Deep Spacial Rift"),
		new("[29, 85]", "the team has encountered Palkia"),
		new("[29, 87]", "the team has learned the location of the Dark Crater"),
		new("[29, 88]", "the team has embarked towards the Dark Crater"),
		new("[29, 90]", "the team has entered the Dark Crater"),
		new("[29, 91]", "Darkrai has begun revealing his role in the Hero's time travel accident"),
		new("[29, 94]", "Chatot has informed the team of Manaphy's return"),
		new("[40, 2]", "Bidoof has completed his errand"),
		new("[41, 3]", "Banette and Skorupi have been revealed as bullies"),
		new("[42, 0]", "Armaldo has scared away Banette and Skorupi"),
		new("[42, 3]", "Armaldo and Igglybuff have been defeated in Eastern Cave")
	]);

	public static Dictionary<string, string> tags = new([
		new(@"c_kind:ATTENDANT1", "`Partner Species`"),
		new(@"c_name:NPC_NEW_FRIEND", "`Friend Name`"),
		new(@"c_kind:PLAYER", "`Hero Species`"),
		new(@"CS:*\w*", "**"),
		new(@"CR:*\w*", "**"),
		new(@"FT:1", "(Unown: "),
		new(@"FT:0", ")"),
		new(@"hero", "`Hero Name`"),
		new(@"player", "`Hero Name`"),
		new(@"K", string.Empty),
		new(@"M:H8", "🤍"),
		new(@"M:I0", "`TM`"),
		new(@"MP", CultureInfo.CurrentCulture.NumberFormat.CurrencyGroupSeparator),
		new(@"partner", "`Partner Name`"),
		new(@"s_item:0", "`Special Item`"),
		new(@"s_item:1", "`Special Item`"),
		new(@"team:", "`Team Name`"),
	]);
}